### ISSUE TITLE
0.9.0 release

### ISSUE THREAD

**Issue by robbertvanginkel** [bazelbuild/bazel-skylib#163]
The last version of bazel skylib was relased on March 20th, almost 3 months ago. Since then a few new rules such as diff_test have been added, and it would be great to be able to consume those from a released version.

Are there any plans to do a new skylib release soon?

**Comment by Globegitter** [comment]
Running into the same issue for rules_nodejs. See https://github.com/bazelbuild/rules_nodejs/pull/863/files#diff-48449ecf6779b035ef4cc8783bd23133R77 - would be great to get a release to depend on instead.

**Comment by meisterT** [comment]
See also the thread that @aiuto started on bazel-dev: https://groups.google.com/forum/#!topic/bazel-dev/fEyp04FSxFc

**Comment by aiuto** [comment]
I just cut a 0.9.0 release https://github.com/bazelbuild/bazel-skylib/releases

This  fiddles with the release notes format a bit. The WORKSPACE section should be directly cut-and-pastable into your WORKSPACE.

Please take a look.

**Comment by nlopezgi** [comment]
There seems to be issues with 0.9.0 release.
See PRs updating in rules_docker and bazel-toolchains:
https://github.com/bazelbuild/rules_docker/pull/992
https://github.com/bazelbuild/bazel-toolchains/pull/630

Error message in both cases is:
```
(01:24:02) ERROR: /var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/org_golang_x_tools/go/internal/gcimporter/BUILD.bazel:18:1: in go_tool_library rule @org_golang_x_tools//go/internal/gcimporter:go_tool_library:
Traceback (most recent call last):
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/org_golang_x_tools/go/internal/gcimporter/BUILD.bazel", line 18
		go_tool_library(name = 'go_tool_library')
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/io_bazel_rules_go/go/private/rules/library.bzl", line 42, in _go_library_impl
		go.archive(go, source)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 207, in go.archive
		GoArchive(source = source, data = data, direct..., <8 more arguments>)
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/io_bazel_rules_go/go/private/actions/archive.bzl", line 211, in GoArchive
		sets.union([searchpath], *[a.searchpaths for ...])
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/bazel_skylib/lib/new_sets.bzl", line 184, in sets.union
		struct(_values = dicts.add(*[s._values ...]))
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/bazel_skylib/lib/new_sets.bzl", line 184, in struct
		dicts.add(*[s._values for s in args])
	File "/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/ec321eb2cc2d0f8f91b676b6d4c66c29/external/bazel_skylib/lib/new_sets.bzl", line 184, in dicts.add
		s._values
object of type 'list' has no field '_values'
```

**Comment by aiuto** [comment]
Do rules_docker and toolchains work with 0.8.0?

**Comment by nlopezgi** [comment]
yes, they both work with 0.8.0, the PRs updating to 0.9.0 were automatically generated by renovate bot to update our pin from 0.8.0 to 0.9.0.

**Comment by aiuto** [comment]
I'm sort of surprised they worked with 0.8.0. I was talking with a go_rules maintainer yesterday who said they had pinned at 0.7.0 because of chante to set. But, that not the point. (and, FWIW, we'll work on updating rules_go).

The real point is that 0.9.0 was a breaking change with some behavior. We should have labeled it 1.0.
Would renovate do the right thing and not try to auto-update on a major version change? 
It would be easy enough to re-release as 1.0.0 and archive 0.9.0.

**Comment by nlopezgi** [comment]
hmm, I'm not too sure how renovate works, but I think it would try to update to 1.0.0. In any case, we like that renovate tries to update with every release and runs CI, so we know as early as possible if there are issues in any of our dependencies. We're fine with ignoring PRs from renovate for releases that are not working, what we dont want is to wait for too long before we realize updates to one of our deps breaks us. Thanks for fixing on rules_go side. Please do let me know when we can try updating skylib again!

**Comment by gregestren** [comment]
Note that the **WORKSPACE setup** notes for 0.9.0 (https://github.com/bazelbuild/bazel-skylib/releases) don't work:

```
maybe(
    http_archive,
    name = "bazel_skylib"     # missing comma
    url = "https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz",
    sha256 = "1dde365491125a3db70731e25658dfdd3bc5dbdfd11b840b3e987ecf043c7ca0",
)
```

**Comment by prestonvanloon** [comment]
What is the solution for the issue mentioned in https://github.com/bazelbuild/bazel-skylib/issues/163#issuecomment-511408099 ? We are also failing when going from 0.8.0 to 0.9.0

**Comment by rarkins** [comment]
Arguably the asset filename used for 0.9.0 is incorrect too:

```
https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz
https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz
```

(Note carefully the use of underscore instead of hyphen between bazel and skylib in the 0.9.0 filename, it's hard to spot)

I think though that it's possible to add an asset to any existing GitHub release, which would solve this aspect.

**Comment by rarkins** [comment]
BTW I noticed that Renovate is warning due to the inability to detect the new URL to generate the new hash, so @nlopezgi I'm a little surprised you got the PR from Renovate at all!

**Comment by aiuto** [comment]
> What is the solution for the issue mentioned in [#163 (comment)](https://github.com/bazelbuild/bazel-skylib/issues/163#issuecomment-511408099) ? We are also failing when going from 0.8.0 to 0.9.0

The solution is don't go to 0.9.0 yet.  No one says you have to be at the most recent revisions. In a very rich and interdependent set of rules maintained by different groups, that is an unattainable goal. There is going to be slow churn while I downstream fix rules_docker and rules_go.

**Comment by aiuto** [comment]
> Arguably the asset filename used for 0.9.0 is incorrect too:
> 
> ```
> https://github.com/bazelbuild/bazel-skylib/releases/download/0.8.0/bazel-skylib.0.8.0.tar.gz
> https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz
> ```
> 
> (Note carefully the use of underscore instead of hyphen between bazel and skylib in the 0.9.0 filename, it's hard to spot)

The filename is not incorrect. It is purposely changed.  The format I am trying to get all of the Bazel team repos into is
     **rules_name**-**version**._ext_
where **rules_name** is the name of the rule set as referenced in WORKSPACE. Repositories should generally use _ in their names. The bazel-skylib repo should have been bazel_skylib.

> I think though that it's possible to add an asset to any existing GitHub release, which would solve this aspect.

Yes. Going forward we are moving to artifact based releases rather than auto-generated tarballs. There are a few reasons for this
- We can distribute minimal rule sets. A rule set might have extensive scaffolding for development that is not needed by its users. We can make a package that just contains the parts users need.
- The file names are meaningful. bazel_skylib-0.9.0.tar.gz is more obvious than just '0.9.0', and far better than <commit_hash>.zip.
- We can get download metrics for explicit artifacts, but not for auto-generated ones. Our goal is to track how often each version of each rule set is downloaded from bazelbuild, then publish that so rule owners can track migration from old versions do the new.

**Comment by nlopezgi** [comment]
> BTW I noticed that Renovate is warning due to the inability to resolve the new URL to generate the new hash, so @nlopezgi I'm a little surprised you got the PR from Renovate at all!

Its because were not using the release url
`https://github.com/bazelbuild/bazel-skylib/releases/download/0.9.0/bazel_skylib-0.9.0.tar.gz`
and instead we are using `https://github.com/bazelbuild/bazel-skylib/archive/0.8.0.tar.gz`, but that's probably an error on our side. Will fix to use the /releases/... tar

**Comment by keith** [comment]
FYI rules_apple/rules_swift/apple_support have all upgrade to 0.9.0 which makes them incompatible with rules_go because of the issues above, is there a good solution to this (or one forthcoming) besides removing the skylib dependency as rules_go seems to be planning to do https://github.com/bazelbuild/rules_go/issues/2157 ?

**Comment by laurentlb** [comment]
Can you first update your code to use `new_sets` instead of `sets`?
Then the update should be smoother.

**Comment by keith** [comment]
Moving rules_go to new_sets also doesn't work because then we hit this same issue sooner

**Comment by aiuto** [comment]
I want to close the loop on this, since this was my fault.

- Moving sets.bzl to old_sets.bzl was a breaking change. I didn't realize this up front. This release should have been labeled as 1.0.0 rather than 0.9.0 to indicate a breaking change.
- All the rules should follow semantic versioning in the same way Bazel does. So dropping an API (like sets working with depsets) always requires a major version change.  So, no way around it - my bad. I did a release that violated semantic versioning.
- If renovate will try to auto-update to new major versions, well, that is basically incompatible with semantic versioning. I do not consider trying to keep up to date with head (which is what this would be) a problem. It is not feasible with multiple components produced by different organizations on un-aligned release cycles.
- rules go solved the issue by dropping the use of skylib sets because it does not meet their needs the way old_sets did. It looks like 0.19.5 came out a few hours ago. https://github.com/bazelbuild/rules_go/releases. That release should not conflict with anyone any more.
- We should do a 1.0.0 release to account for the 0.9.0 naming problem (#193). This should keep old_sets so we give people migration time. We can drop old_sets at skylib 2.0.0.  The choice of when that happens is not obvious. The federation can only adopt the breaking change after enough rules have converted. If we drop old_sets too early, no one will get to use any new features.
- I recognize that sometimes the only tenable way for rule authors to get their job done is to pin some of their dependencies to particular releases. Guidance for how to do that as part of the federation is here: https://bazelbuild.github.io/bazel-federation/how_to_integrate.html. TL;DR; You can do it, but you can't use the canonical name for the pinned repository.

**Comment by aiuto** [comment]
cc: @fweikert @jayconrod

**Comment by rarkins** [comment]
According to semver's spec, anything <1.0.0 can always be a breaking change. Theoretically, there was no mistake by failing to bump to 1.0.0. The mistake (still existing) is that a production library like this shouldn't be running on <1.0.0. Literally any update from 0.8.0 to anything is considered potentially breaking (even 0.8.0 -> 0.8.1, although by convention most library authors would not make breaking changes in a pre-1.0.0 patch).

Pre-1.0.0 versioning should only be used in the Bazel ecosystem for libraries that are considered not ready for production. Anything which people might be depending on for production should be updated to 1.0.0 ASAP and then major releases used to indicate breaking changes. There is no shame in multiple major updates in a year for libraries. It's a much superior user experience than having to check carefully if each pre-1.0.0 update is breaking or not (most are not).

> If renovate will try to auto-update to new major versions, well, that is basically incompatible with semantic versioning

This is a misunderstanding. Renovate exists to update dependencies. If a library you depend on updates from 0.8.0 to 1.0.0 then of course you would expect Renovate to tell you about it via an automated PR. It's then up to the human to evaluate what's changed and if it's suitable to merge. Renovate does not auto-merge anything by default unless users specifically configure it too, and I'd never recommend automerging major releases.

**Comment by jayconrod** [comment]
About rules_go: the change to remove the dependency on `old_sets.bzl` is not on a release branch yet. In order to stop using `old_sets.bzl`, I deleted a fair amount of legacy code, rather than migrating it. That change can't be backported to the `release-0.19` branch, so it will be in the `v0.20.0` release, which is probably still a few weeks away. @aiuto Let me know if I should push the release out sooner.

**Comment by aiuto** [comment]
obsolete. we are a few versions beyond 0.9 now
